baseURL = "https://blog.m0n4.com"
languageCode = "ja-jp" 
title = "水の飲み方を忘れないための備忘録"
theme = "m10c"
paginate = 8

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "記事一覧(カテゴリ)"
    url = "/categories"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "記事一覧(タグ)"
    url = "/tags"
    weight = 3

[params]
  author = "Lutwidse"
  description = "メモ帳として使う予定"
  avatar = "/site/avatar.webp"
  favicon = "/site/favicon.ico"
  menu_item_separator = " <br> "
  images = ["/site/avatar.webp"]
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Lutwidse"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/Lutwidse0xff"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#f5fffa"
    primaryColor = "#c2c4c6"
    textColor = "#fffff0"